import { useEffect, useState } from "react";

import Navbar from "../../ui/components/Navbar";
import Footer from "../../ui/components/Footer";
import ReportCard from "../components/ReportCard";

const InterviewReport = () => {
  const [reports, setReports] = useState([]);

  // temporary dummy data
  useEffect(() => {
    setReports([
      {
        _id: "1",
        title: "Full Stack Developer Intern",
        jobDescription:
          "AI Startup Impact is hiring Full Stack Developer Intern...",
        matchScore: 85,
        createdAt: new Date(),
      },
      {
        _id: "2",
        title: "Frontend Developer",
        jobDescription: "Frontend React Developer for SaaS Product...",
        matchScore: 79,
        createdAt: new Date(),
      },
    ]);
  }, []);

  return (
    <div className="min-h-screen bg-[#0F0F0F] text-white flex flex-col">
      <Navbar />

      <main className="flex-1 pt-30 px-6 pb-10">
        <div className="max-w-6xl mx-auto">
          <h1 className="text-4xl font-bold">Interview Reports</h1>

          <p className="text-zinc-500 mt-3">
            View every interview report generated by HireZen AI.
          </p>

          <div className="grid lg:grid-cols-2 gap-6 mt-10">
            {reports.map((report) => (
              <ReportCard key={report._id} report={report} />
            ))}
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default InterviewReport;
